name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    type: [rerequested]

jobs:
  chroot-testing:
    runs-on: ubuntu-20.04
    steps:
    - name: Installs qemu-riscv64-static
      run: |
        sudo apt-get install -q debootstrap qemu-user-static binfmt-support debian-ports-archive-keyring
#    - name: Builds a Debian Chroot
#        sudo debootstrap --arch=riscv64 --keyring /usr/share/keyrings/debian-ports-archive-keyring.gpg --include=debian-ports-archive-keyring unstable debian-riscv64-chroot http://deb.debian.org/debian-ports
#        sudo cp $(which qemu-riscv64-static) debian-riscv64-chroot/usr/bin
#    - name: Basic test of Debian Chroot
#      run: |
#        sudo chroot debian-riscv64-chroot/ qemu-riscv64-static /bin/true
#        sudo find debian-riscv64-chroot/
#        sudo du -shc debian-riscv64-chroot/
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Builds a Slackware-riscv64 Chroot
      run: |
        chroot=slackware-riscv64-chroot
        mkdir -p $chroot/sbin
        tar xfvJ slackware-current/slackware/a/pkgtools-15.0-noarch-6.txz sbin/installpkg
        sudo mv sbin/installpkg /sbin/
        rmdir sbin/
        find slackware-current/slackware/ -type f -name aaa\*txz -exec sudo installpkg --root $chroot {} \;
        find slackware-current/slackware/ -type f -name *txz -exec sudo installpkg --root $chroot {} \;
        sudo cp $(which qemu-riscv64-static) $chroot/usr/bin
    - name: Basic test of Slackware-riscv64 Chroot
      run: |
        sudo find slackware-riscv64-chroot
        sudo du -shc slackware-riscv64-chroot
        echo "Packages in repo: $(find slackware/ -type f -name *txz|wc -l)"
        echo "Chroot size: $(du -sh slackware-riscv64-chroot | awk '{print $1}' )"
        sudo chroot slackware-riscv64-chroot qemu-riscv64-static /bin/true
